version: '3.4'

services:
  cityopencv1:
    image: cityopencv1
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 script1.py "]
    ports:
      - 5678:5678
