version: '3.4'

services:
  cityopencv1:
    image: cityopencv1
    build:
      context: .
      dockerfile: ./Dockerfile
    healthcheck:
      test: CMD["executable", "arg"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s